# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# rbs-inlineでメソッドの後ろに `#: ` を使うため
Style/CommentedKeyword:
  Enabled: false

# rbs-inlineで `#: ` を使うため
Layout/LeadingCommentSpace:
  Enabled: false

# rbs-inlineでは　`attr_*` を1つずつ書く必要があるため
Style/AccessorGrouping:
  Enabled: false
